services:

  postgres:
    container_name: postgres
    image: postgres:12.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - .data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prestgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    depends_on:
      - postgres
  
  dbt:
    container_name: dbt-postgres
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/dbt
    depends_on:
      postgres:
        condition: service_healthy